# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/martin/repos/c/msync

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/martin/repos/c/msync

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/martin/repos/c/msync/CMakeFiles /Users/martin/repos/c/msync//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/martin/repos/c/msync/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kevent

# Build rule for target.
kevent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kevent
.PHONY : kevent

# fast build rule for target.
kevent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kevent.dir/build.make CMakeFiles/kevent.dir/build
.PHONY : kevent/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

client.o: client.c.o

.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i

.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s

.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.s
.PHONY : client.c.s

src/kfs.o: src/kfs.c.o

.PHONY : src/kfs.o

# target to build an object file
src/kfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kevent.dir/build.make CMakeFiles/kevent.dir/src/kfs.c.o
.PHONY : src/kfs.c.o

src/kfs.i: src/kfs.c.i

.PHONY : src/kfs.i

# target to preprocess a source file
src/kfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kevent.dir/build.make CMakeFiles/kevent.dir/src/kfs.c.i
.PHONY : src/kfs.c.i

src/kfs.s: src/kfs.c.s

.PHONY : src/kfs.s

# target to generate assembly for a file
src/kfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kevent.dir/build.make CMakeFiles/kevent.dir/src/kfs.c.s
.PHONY : src/kfs.c.s

tests/darray_tests.o: tests/darray_tests.c.o

.PHONY : tests/darray_tests.o

# target to build an object file
tests/darray_tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/darray_tests.c.o
.PHONY : tests/darray_tests.c.o

tests/darray_tests.i: tests/darray_tests.c.i

.PHONY : tests/darray_tests.i

# target to preprocess a source file
tests/darray_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/darray_tests.c.i
.PHONY : tests/darray_tests.c.i

tests/darray_tests.s: tests/darray_tests.c.s

.PHONY : tests/darray_tests.s

# target to generate assembly for a file
tests/darray_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/darray_tests.c.s
.PHONY : tests/darray_tests.c.s

tests/hashmap_tests.o: tests/hashmap_tests.c.o

.PHONY : tests/hashmap_tests.o

# target to build an object file
tests/hashmap_tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/hashmap_tests.c.o
.PHONY : tests/hashmap_tests.c.o

tests/hashmap_tests.i: tests/hashmap_tests.c.i

.PHONY : tests/hashmap_tests.i

# target to preprocess a source file
tests/hashmap_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/hashmap_tests.c.i
.PHONY : tests/hashmap_tests.c.i

tests/hashmap_tests.s: tests/hashmap_tests.c.s

.PHONY : tests/hashmap_tests.s

# target to generate assembly for a file
tests/hashmap_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/hashmap_tests.c.s
.PHONY : tests/hashmap_tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... kevent"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... src/kfs.o"
	@echo "... src/kfs.i"
	@echo "... src/kfs.s"
	@echo "... tests/darray_tests.o"
	@echo "... tests/darray_tests.i"
	@echo "... tests/darray_tests.s"
	@echo "... tests/hashmap_tests.o"
	@echo "... tests/hashmap_tests.i"
	@echo "... tests/hashmap_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

